import { StaffMember, Session, ColumnId } from './types';

export const INITIAL_STAFF: StaffMember[] = [
  // PTs
  { id: 'agnes', name: 'Agnes', role: 'PT', defaultColor: 'white' },
  { id: 'andrew', name: 'Andrew', role: 'PT', defaultColor: 'white' },
  { id: 'annie', name: 'Annie', role: 'PT', defaultColor: 'white' },
  { id: 'arthur', name: 'Arthur', role: 'PT', defaultColor: 'white' },
  { id: 'ashley', name: 'Ashley', role: 'PT', defaultColor: 'white' },
  { id: 'cedric', name: 'Cedric', role: 'PT', defaultColor: 'white' },
  { id: 'denise', name: 'Denise', role: 'PT', defaultColor: 'white' },
  { id: 'e_chang', name: 'E Chang', role: 'PT', defaultColor: 'white' },
  { id: 'elaine', name: 'Elaine', role: 'PT', defaultColor: 'white' },
  { id: 'eric', name: 'Eric', role: 'PT', defaultColor: 'white' },
  { id: 'frankie', name: 'Frankie', role: 'PT', defaultColor: 'white' },
  { id: 'george', name: 'George', role: 'PT', defaultColor: 'white' },
  { id: 'gigi_pt', name: 'Gigi', role: 'PT', defaultColor: 'white' },
  { id: 'ham', name: 'Ham', role: 'PT', defaultColor: 'white' },
  { id: 'henry', name: 'Henry', role: 'PT', defaultColor: 'white' },
  { id: 'hy', name: 'HY', role: 'PT', defaultColor: 'white' },
  { id: 'jamie', name: 'Jamie', role: 'PT', defaultColor: 'white' },
  { id: 'jamie_ip', name: 'Jamie IP', role: 'PT', defaultColor: 'white' },
  { id: 'jessie', name: 'Jessie', role: 'PT', defaultColor: 'white' },
  { id: 'karen_pt', name: 'Karen', role: 'PT', defaultColor: 'white' },
  { id: 'kelly', name: 'Kelly', role: 'PT', defaultColor: 'white' },
  { id: 'ken', name: 'Ken', role: 'PT', defaultColor: 'white' },
  { id: 'leo', name: 'Leo', role: 'PT', defaultColor: 'white' },
  { id: 'leon_y', name: 'Leon Y', role: 'PT', defaultColor: 'white' },
  { id: 'm_chan', name: 'M Chan', role: 'PT', defaultColor: 'white' },
  { id: 'michelle_h', name: 'Michelle H', role: 'PT', defaultColor: 'white' },
  { id: 'peter', name: 'Peter', role: 'PT', defaultColor: 'white' },
  { id: 'polly', name: 'Polly', role: 'PT', defaultColor: 'white' },
  { id: 'primo', name: 'Primo', role: 'PT', defaultColor: 'white' },
  { id: 'richard', name: 'Richard', role: 'PT', defaultColor: 'white' },
  { id: 'sophia', name: 'Sophia', role: 'PT', defaultColor: 'white' },
  { id: 'stephy', name: 'Stephy', role: 'PT', defaultColor: 'white' },
  { id: 'summer', name: 'Summer', role: 'PT', defaultColor: 'white' },
  { id: 't_chan', name: 'T Chan', role: 'PT', defaultColor: 'white' },
  { id: 't_mak', name: 'T Mak', role: 'PT', defaultColor: 'white' },
  { id: 't_yip', name: 'T Yip', role: 'PT', defaultColor: 'white' },
  { id: 'victor', name: 'Victor', role: 'PT', defaultColor: 'white' },
  { id: 'william', name: 'William', role: 'PT', defaultColor: 'white' },
  { id: 'yan', name: 'Yan', role: 'PT', defaultColor: 'white' },
  { id: 'yannie', name: 'Yannie', role: 'PT', defaultColor: 'white' },
  { id: 'yuen_ching', name: 'Yuen Ching', role: 'PT', defaultColor: 'white' },

  // Support / PCA
  { id: 'ria', name: 'Ria', role: 'Support', defaultColor: 'white' },
  { id: 'mable', name: 'Mable', role: 'Support', defaultColor: 'white' },
  { id: 'ann', name: 'Ann', role: 'Support', defaultColor: 'white' },
  { id: 'wei', name: '威', role: 'Support', defaultColor: 'white' },
  { id: 'clara', name: 'Clara', role: 'Support', defaultColor: 'white' },
  { id: 'cherie', name: 'Cherie', role: 'Support', defaultColor: 'white' },
  { id: 'jason', name: 'Jason', role: 'Support', defaultColor: 'white' },
  { id: 'angel', name: 'Angel', role: 'Support', defaultColor: 'white' },
  { id: 'fion', name: 'Fion', role: 'Support', defaultColor: 'white' },
  { id: 'christy', name: 'Christy', role: 'Support', defaultColor: 'white' },
  { id: 'paul', name: 'Paul', role: 'Support', defaultColor: 'white' },
  { id: 'connie', name: 'Connie', role: 'Support', defaultColor: 'white' },
  { id: 'gloria', name: 'Gloria', role: 'Support', defaultColor: 'white' },
  { id: 'winnie', name: 'Winnie', role: 'Support', defaultColor: 'white' },
  { id: 'carmen', name: 'Carmen', role: 'Support', defaultColor: 'white' },
  { id: 'wendy', name: 'Wendy', role: 'Support', defaultColor: 'white' },
  { id: 'allie', name: 'Allie', role: 'Support', defaultColor: 'white' },
  { id: 'karen_sup', name: 'Karen', role: 'Support', defaultColor: 'white' },
  { id: 'wing', name: 'Wing', role: 'Support', defaultColor: 'white' },
];

export const SESSIONS: Session[] = ['1st', '2nd', '3rd', '4th'];

export const COLUMNS: { id: ColumnId; label: string; group?: 'Team 1' | 'Team 2' | 'PCA' }[] = [
  { id: 'T1_PTI', label: 'APPT', group: 'Team 1' },
  { id: 'T1_PTII', label: 'RPT', group: 'Team 1' },
  { id: 'T2_PTI', label: 'APPT', group: 'Team 2' },
  { id: 'T2_PTII', label: 'RPT', group: 'Team 2' },
  { id: 'PCA', label: 'PCA', group: 'PCA' },
];